var namespacereg =
[
    [ "AbstractWrapper", "structreg_1_1_abstract_wrapper.html", "structreg_1_1_abstract_wrapper" ],
    [ "CHECK", "structreg_1_1_c_h_e_c_k.html", "structreg_1_1_c_h_e_c_k" ],
    [ "Combined", "structreg_1_1_combined.html", null ],
    [ "CompositeOpacity", "structreg_1_1_composite_opacity.html", null ],
    [ "Fixed", "structreg_1_1_fixed.html", null ],
    [ "Interpolator", "structreg_1_1_interpolator.html", null ],
    [ "is_stl", "structreg_1_1is__stl.html", null ],
    [ "is_stl< std::string >", "structreg_1_1is__stl_3_01std_1_1string_01_4.html", null ],
    [ "is_stl< std::vector< T, Alloc > >", "structreg_1_1is__stl_3_01std_1_1vector_3_01_t_00_01_alloc_01_4_01_4.html", null ],
    [ "ITKtoVTK", "structreg_1_1_i_t_kto_v_t_k.html", "structreg_1_1_i_t_kto_v_t_k" ],
    [ "Method", "structreg_1_1_method.html", null ],
    [ "Metric", "structreg_1_1_metric.html", null ],
    [ "Monitor", "structreg_1_1_monitor.html", null ],
    [ "Moving", "structreg_1_1_moving.html", null ],
    [ "Optimizer", "structreg_1_1_optimizer.html", null ],
    [ "Reader", "structreg_1_1_reader.html", "structreg_1_1_reader" ],
    [ "Registrator", "structreg_1_1_registrator.html", "structreg_1_1_registrator" ],
    [ "Resampler", "structreg_1_1_resampler.html", null ],
    [ "Transform", "structreg_1_1_transform.html", null ],
    [ "TransformInitializer", "structreg_1_1_transform_initializer.html", null ],
    [ "Visualizer", "structreg_1_1_visualizer.html", "structreg_1_1_visualizer" ],
    [ "Wrapper", "structreg_1_1_wrapper.html", null ],
    [ "WrapperBase", "structreg_1_1_wrapper_base.html", null ],
    [ "WrapperBase< T, itk::SmartPointer< T > >", "structreg_1_1_wrapper_base_3_01_t_00_01itk_1_1_smart_pointer_3_01_t_01_4_01_4.html", "structreg_1_1_wrapper_base_3_01_t_00_01itk_1_1_smart_pointer_3_01_t_01_4_01_4" ],
    [ "WrapperBase< T, std::unique_ptr< T > >", "structreg_1_1_wrapper_base_3_01_t_00_01std_1_1unique__ptr_3_01_t_01_4_01_4.html", "structreg_1_1_wrapper_base_3_01_t_00_01std_1_1unique__ptr_3_01_t_01_4_01_4" ],
    [ "WrapperBase< T, vtkSmartPointer< T > >", "structreg_1_1_wrapper_base_3_01_t_00_01vtk_smart_pointer_3_01_t_01_4_01_4.html", "structreg_1_1_wrapper_base_3_01_t_00_01vtk_smart_pointer_3_01_t_01_4_01_4" ],
    [ "Writer", "structreg_1_1_writer.html", "structreg_1_1_writer" ]
];